version: "3.9"

services:
  frontend:
    container_name: fullstack-auth-frontend
    build:
      context: ./
      dockerfile: Dockerfile
      args:
        API_URL: ${API_URL:-https://chermanx.ru/api}
        YANDEX_CLIENT_ID: ${YANDEX_CLIENT_ID:-}
        YANDEX_REDIRECT_URI: ${YANDEX_REDIRECT_URI:-https://chermanx.ru/signin}
    restart: unless-stopped
    env_file:
      - .env
    ports:
      - "0.0.0.0:${PORT:-4173}:4173"
    environment:
      NODE_ENV: production
    networks:
      - frontend-network

networks:
  frontend-network:
    name: fullstack-auth-frontend
    driver: bridge
