version: "3.9"

services:
  frontend:
    build:
      context: ./
      dockerfile: Dockerfile
      args:
        VITE_APP_NAME: ${VITE_APP_NAME:-Fullstack Auth}
        VITE_API_URL: ${VITE_API_URL}
        VITE_YANDEX_CLIENT_ID: ${VITE_YANDEX_CLIENT_ID}
        VITE_YANDEX_REDIRECT_URI: ${VITE_YANDEX_REDIRECT_URI}
    restart: unless-stopped
    env_file:
      - .env
    ports:
      - "${FRONTEND_PORT:-4173}:4173"
    networks:
      - frontend-network

networks:
  frontend-network:
    name: fullstack-auth-frontend
    driver: bridge
